web/router.ex
defmodule Studentmanager.Router do
  use Studentmanager.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Studentmanager.Auth, repo: Studentmanager.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Studentmanager do
    pipe_through :browser 

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/info", PageController, :info
    get "/info/:instrument", PageController, :info

    get "register", UserController, :new
    get "/my_account", ProfileController, :show

    resources "/profiles", ProfileController
    resources "/students", StudentController

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end
  scope "/admin", Studentmanager do
    pipe_through :browser

    resources "/users", UserController
  end
end

web/views/layout_view.ex
defmodule Studentmanager.LayoutView do
  use Studentmanager.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Studentmanager | Manage your students with ease!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
          <a class="navbar-brand" href="/">Student Manager</a>
          <ul class="nav navbar-nav">
            <%= if @current_user do %>
              <li><%= link "Students", to: student_path(@conn, :index) %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <%= if @current_user do %>
              <li><a href='/my_account'><%= @current_user.username %></a></li>
              <li><%= link "Log Out", to: session_path(@conn, :delete, @current_user), method: "delete", class: "navbar-text" %></li> 
            <% else %>
              <li><%= link "Login", to: session_path(@conn, :new)  %></li>
              <li><%= link "Register", to: user_path(@conn, :new)  %></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
      <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>